import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../../components/Navbar'
import styles from '../../styles/Home.module.css'
import api from '../../services/api'
import Form from '../../components/Form'

export default function EditUser({user}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
        <h1 className={styles.title}>Editar Usuário</h1>
          <Form user={user}/>
      </main>
    </>
  )
}
EditUser.getInitialProps = async ({query: { id }}) => {
    const { data } = await api.get(`/${id}`)
    return {user: data}
}