import React from 'react'
import Head from 'next/head'
import {
    Box,
    Center,
    Heading,
    Text,
    Stack,
    Avatar,
    useColorModeValue,
  } from '@chakra-ui/react';
  
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import api from '../services/api'

export default function ShowUser({user}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
        <h1 className={styles.title}>Área do Usuário</h1>
        <Center py={6}>
      <Box
        maxW={'445px'}
        w={'full'}
        bg={useColorModeValue('white', 'gray.900')}
        boxShadow={'2xl'}
        rounded={'md'}
        p={6}
        overflow={'hidden'}>
        <Stack>
          <Text
            color={'green.500'}
            textTransform={'uppercase'}
            fontWeight={800}
            fontSize={'sm'}
            letterSpacing={1.1}>
            Usuário
          </Text>
          <Heading
            color={useColorModeValue('gray.700', 'white')}
            fontSize={'2xl'}
            fontFamily={'body'}>
            {user.name}
          </Heading>
          <Text color={'gray.500'}>{user.email}</Text>
          <Text color={'gray.500'}>{user.age} anos</Text>
          <Text color={'gray.500'}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam consectetur pulvinar faucibus. Cras et aliquet metus. Duis eget fermentum mauris, quis ornare sapien. Aenean scelerisque nunc quis nibh sollicitudin, nec malesuada quam semper. Etiam enim eros, vulputate eget elit non, fringilla eleifend orci. Cras diam neque, feugiat non mauris a, gravida placerat velit. Maecenas aliquet rhoncus nibh ac porttitor. Aliquam tristique accumsan lorem, ac ultricies tellus laoreet a. Donec blandit purus ut quam mollis, et tristique arcu eleifend. Praesent in libero sollicitudin, lacinia magna dignissim, laoreet ligula. Donec in malesuada odio.
        </Text>
        </Stack>
      </Box>
    </Center>
      </main>
    </>
  )
}
export async function getServerSideProps({query: { id }}) {
  const { data } = await api.get(`/${id}`)
  return {
    props: {user: data}, 
  }
}
