import Head from 'next/head'
import Navbar from '../components/Navbar'
import Table from '../components/Table'
import styles from '../styles/Home.module.css'
import api from '../services/api'
export default function Index({users}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
        <h1 className={styles.title}>Usuários</h1>
          <Table users={users} />
      </main>
    </>
  )
}
export async function getServerSideProps() {
  const { data } = await api.get('/')
  return {
    props: {users: data}, 
  }
}